import type { MagazinePage } from './editor-types';

const rows = [
  ['cover', 'Val Advogado', 'Edição 01 - 2026', 'O que eu faço é da sua conta.', 'Uma vida transformada pela educação. Um mandato dedicado a transformar outras vidas.'],
  ['biography', 'Filho de um pedreiro e de uma bordadeira.', 'Quem é Val?', 'Val Advogado construiu sua trajetória a partir de uma origem humilde, marcada por trabalho, família e estudo. A educação abriu caminhos, permitiu sua formação como advogado e se tornou a base de uma vida pública voltada a criar oportunidades para quem mais precisa.', 'Educação mudou a minha vida. Agora, o mandato trabalha para transformar outras vidas.'],
  ['mosaic', 'Origem, família e compromisso público.', 'Trajetória', 'A história pessoal de Val ajuda a explicar seu jeito de atuar: perto das pessoas, atento às famílias e comprometido com respostas concretas. No mandato, demandas da população viram fiscalização, projetos, leis, indicações e busca permanente por recursos para Guarujá.', 'A política precisa estar onde as pessoas estão.'],
  ['editorial-dark', 'Guarujá e Brasília conectados.', 'Parceria com Renata Abreu', 'A parceria entre Val Advogado e a deputada federal Renata Abreu funciona como uma ponte entre as necessidades de Guarujá e as decisões tomadas em Brasília. Val conhece de perto as demandas da cidade; Renata fortalece essa voz na esfera federal.', 'Uma parceria construída em torno de causas em comum e resultados concretos.'],
  ['photo-story', 'R$ 2 milhões para segurança.', 'Resultado concreto', 'Um dos resultados dessa parceria foi a conquista de R$ 2 milhões para investimentos em segurança, com foco no fortalecimento do videomonitoramento. Também houve articulação de recursos para o terceiro setor, incluindo apoio à APAAG.', 'Segurança se faz com investimento, tecnologia e presença do poder público.'],
  ['autism-intro', 'Mais de R$ 1 milhão para inclusão e TEA.', 'Inclusão', 'Garantir inclusão exige investimento, estrutura e atendimento especializado. Por isso, o mandato destinou mais de R$ 1 milhão em emendas impositivas para instituições que acolhem pessoas autistas, ampliam terapias e apoiam famílias atípicas.', 'Cuidar também de quem cuida.'],
  ['autism-actions', 'APAAG - R$ 385 mil.', 'Atendimento especializado', 'Os recursos destinados à APAAG fortalecem o atendimento de jovens e adultos neurodivergentes. A iniciativa permite ampliar acompanhamento com profissionais como neuropediatra, psiquiatra e outros especialistas, promovendo diagnóstico, continuidade e cuidado humanizado.', 'Inclusão também é acesso ao tratamento certo, no tempo certo.'],
  ['autism-family', 'Projeto Universo - R$ 503 mil.', 'Rede multidisciplinar', 'A emenda destinada ao Projeto Universo reforça a estrutura física da instituição e amplia a equipe multidisciplinar. O investimento contempla neuropsicólogo, psicopedagoga, fisioterapeuta, apoio psicológico e assistência social para mães atípicas.', 'Quando a família é acolhida, o cuidado fica mais forte.'],
  ['autism-guide', 'Pequenos Herdeiros - R$ 200 mil.', 'Desenvolvimento infantil', 'A destinação para a Pequenos Herdeiros melhora a estrutura, apoia a aquisição de materiais e fortalece a contratação de profissionais especializados. O objetivo é ampliar atendimentos e oferecer às crianças atípicas um ambiente mais preparado para seu desenvolvimento.', 'Inclusão precisa de ambiente preparado, equipe e continuidade.'],
  ['projects', 'Educação especial e acessibilidade.', 'Cidade inclusiva', 'O mandato atua por capacitação continuada de professores sobre autismo, substituição de sirenes agressivas, reserva de assento para acompanhantes de pessoas com deficiência ou TEA e cardápios em braille em estabelecimentos comerciais.', 'Acessibilidade é autonomia na prática.'],
  ['fight-intro', 'Mais de R$ 710 mil para o esporte.', 'Esporte social', 'Val acredita no esporte como ferramenta de disciplina, convivência e transformação social. Mais de R$ 710 mil em emendas foram direcionados a projetos esportivos que atendem crianças, adolescentes, jovens e adultos em diferentes bairros.', 'Cada treino pode abrir caminho para um futuro melhor.'],
  ['fight-gallery', 'Modalidades que formam cidadãos.', 'Atletas e projetos', 'Muay thai, boxe, jiu-jitsu, kickboxing, wrestling, natação, futebol e tênis de mesa fazem parte da rede apoiada. O incentivo chega em materiais, equipamentos, estrutura, divulgação e articulação de oportunidades.', 'Disciplina, convivência e respeito também são políticas públicas.'],
  ['fight-network', 'Amigos da Elite, HM Clan e Vila Zilda.', 'Entidades esportivas', 'As emendas fortalecem instituições como Amigos da Elite, HM Clan e Sociedade Representativa da Vila Zilda. São projetos que oferecem treino, convivência, festivais e modalidades esportivas como ferramenta de inclusão e pertencimento.', 'Uma rede forte transforma talento em oportunidade.'],
  ['timeline', 'Saúde com acesso e futuro.', 'Saúde pública', 'Na saúde, Val defende a implantação da telemedicina, cobra mutirões de atendimento especializado e acompanha os avanços do futuro Hospital Municipal. Também propõe ampliar tratamentos e garantir mais estrutura à rede pública.', 'Saúde digna começa com acesso, escuta e acompanhamento.'],
  ['projects', 'Lei nº 5.303: microchipagem gratuita.', 'Proteção animal', 'A causa animal ganhou uma conquista importante com a Lei nº 5.303, que prevê microchipagem gratuita de cães e gatos e cadastro no Simpatinhas. O mandato também defende castrações, atendimento veterinário e combate ao abandono.', 'Cuidar dos animais também é cuidar da cidade.'],
  ['commitments', 'Água, saneamento e fiscalização.', 'Serviços públicos', "Val atua na cobrança de soluções para falta d'água, baixa pressão, vazamentos e interrupções sem justificativa. Também apresenta indicações para desassoreamento de rios e canais, buscando reduzir alagamentos e melhorar a qualidade urbana.", 'Problema recorrente precisa de cobrança constante.'],
  ['projects', 'Direitos das mulheres e rede de proteção.', 'Disque 180', 'A divulgação obrigatória do Disque 180 amplia o acesso à informação para mulheres vítimas de violência. A atuação também inclui conscientização, prevenção e apoio ao fortalecimento da rede municipal de proteção.', 'Informação salva vidas e aproxima ajuda.'],
  ['visual-diary', 'Empreendedorismo e geração de renda.', 'Desenvolvimento', 'O mandato trabalha pela modernização das regras do comércio eletrônico municipal, apoio aos pequenos empreendedores, desburocratização e criação de oportunidades para comerciantes, trabalhadores locais e novas iniciativas econômicas.', 'Desenvolver é abrir caminho para quem trabalha.'],
  ['participation', 'Da escuta ao resultado.', 'Como trabalhamos', 'As demandas chegam pelas ruas, pelo gabinete e pelos canais digitais. A partir daí, o mandato registra, verifica, fiscaliza, propõe encaminhamentos e presta contas para que a população acompanhe cada etapa.', 'Transparência é mostrar o que aconteceu depois da conversa.'],
  ['final-back-cover', 'O gabinete está de portas abertas.', 'Faça parte', 'Envie sugestões, acompanhe projetos, participe das decisões que impactam a cidade e cobre resultados. O mandato existe para ouvir, agir e prestar contas de forma clara à população de Guarujá.', 'O que eu faço é da sua conta.'],
];

export const fallbackPages: MagazinePage[] = rows.map((row, index) => ({
  id: `fallback-${index + 1}`,
  page_number: index + 1,
  template: row[0],
  title: row[1],
  subtitle: row[2],
  body: row[3],
  quote: row[4] || null,
  background: null,
  elements: {},
  is_published: true,
}));
