import type { MagazinePage } from './editor-types';

const rows = [
  ['cover', 'Val Advogado', 'Edição 01 - 2026', 'Presença que cuida. Trabalho que transforma.', 'Uma vida transformada pela educação. Um mandato dedicado a transformar outras vidas.'],
  ['biography', 'Filho de uma bordadeira e de um mestre de obras.', 'Quem é Val?', 'Valdemir Batista Santana, o Val Advogado, nasceu em Guarujá e cresceu no bairro Paecara, em Vicente de Carvalho. Sua trajetória começou em uma família trabalhadora, com valores de esforço, estudo e responsabilidade. A educação abriu caminhos, permitiu sua formação como advogado e consolidou uma visão de mandato voltada a oportunidades reais para quem mais precisa.', 'Educação mudou a minha vida. Agora, o mandato trabalha para transformar outras vidas.'],
  ['mosaic', 'Uma história pública construída perto das pessoas.', 'Trajetória', 'Com mais de duas décadas de experiência na política, Val atuou como assessor parlamentar, diretor e chefe de gabinete antes de exercer mandato como vereador. Essa vivência ajudou a formar um estilo de trabalho baseado em escuta, acompanhamento e cobrança. As demandas que chegam das ruas viram fiscalização, projetos, indicações, leis e busca por recursos para Guarujá.', 'A política precisa estar onde as pessoas estão.'],
  ['editorial-dark', 'Guarujá e Brasília conectados por resultados.', 'Parceria com Renata Abreu', 'A parceria entre Val Advogado e a deputada federal Renata Abreu aproxima as necessidades de Guarujá das decisões tomadas em Brasília. Val identifica as demandas locais, organiza prioridades e acompanha o impacto na cidade. A deputada fortalece essa voz na esfera federal, abrindo caminho para investimentos em segurança, inclusão e terceiro setor.', 'Ponte política boa é aquela que começa na escuta e termina em entrega.'],
  ['photo-story', 'R$ 2 milhões para segurança pública.', 'Resultado concreto', 'Um dos resultados dessa articulação foi a conquista de R$ 2 milhões para investimentos em segurança, com foco no fortalecimento do videomonitoramento. A pauta une tecnologia, prevenção e presença do poder público. Também houve encaminhamento de recursos para instituições sociais, incluindo apoio à APAAG e a projetos que cuidam de famílias, crianças, jovens e pessoas com deficiência.', 'Segurança se faz com investimento, tecnologia e presença do poder público.'],
  ['autism-intro', 'Mais de R$ 1 milhão para inclusão e TEA.', 'Inclusão', 'Garantir inclusão exige mais do que discurso: exige orçamento, equipe, estrutura e continuidade. Por isso, o mandato destinou mais de R$ 1 milhão em emendas impositivas para instituições que acolhem pessoas autistas, ampliam terapias, fortalecem diagnósticos, apoiam famílias atípicas e cuidam também de mães, pais e cuidadores que sustentam essa rede todos os dias.', 'Cuidar também de quem cuida.'],
  ['autism-actions', 'APAAG - R$ 385 mil.', 'Atendimento especializado', 'Os recursos destinados à APAAG fortalecem o atendimento de jovens e adultos neurodivergentes. A iniciativa contribui para ampliar acompanhamento com profissionais especializados, organizar rotinas de cuidado, promover diagnósticos, apoiar famílias e reduzir a distância entre a necessidade e o tratamento adequado. Inclusão, aqui, significa acesso, acolhimento e permanência.', 'Inclusão também é acesso ao tratamento certo, no tempo certo.'],
  ['autism-family', 'Projeto Universo - R$ 503 mil.', 'Rede multidisciplinar', 'A emenda destinada ao Projeto Universo reforça a estrutura física da instituição e amplia a equipe multidisciplinar. O investimento contempla neuropsicólogo, psicopedagoga, fisioterapeuta, apoio psicológico e assistência social para mães atípicas. A proposta é fortalecer a criança, orientar a família e criar uma rede de cuidado com mais preparo e humanidade.', 'Quando a família é acolhida, o cuidado fica mais forte.'],
  ['autism-guide', 'Pequenos Herdeiros - R$ 200 mil.', 'Desenvolvimento infantil', 'A destinação para a Pequenos Herdeiros melhora a estrutura, apoia a aquisição de materiais e fortalece a contratação de profissionais especializados. O foco é ampliar atendimentos e oferecer às crianças atípicas um ambiente preparado para desenvolvimento, convivência, estímulo e aprendizagem, com atenção ao ritmo e às necessidades de cada família.', 'Inclusão precisa de ambiente preparado, equipe e continuidade.'],
  ['projects', 'Educação especial e acessibilidade.', 'Cidade inclusiva', 'O mandato atua por capacitação continuada de professores sobre autismo, substituição de sirenes agressivas por sinais mais adequados, reserva de assento para acompanhantes de pessoas com deficiência ou TEA e cardápios em braille em estabelecimentos comerciais. São medidas práticas para transformar acolhimento em rotina da cidade.', 'Acessibilidade é autonomia na prática.'],
  ['fight-intro', 'Mais de R$ 710 mil para o esporte.', 'Esporte social', 'Val defende o esporte como ferramenta de disciplina, convivência, saúde e transformação social. Mais de R$ 710 mil em emendas foram direcionados a projetos esportivos que atendem crianças, adolescentes, jovens e adultos em diferentes bairros. Quando a cidade apoia o esporte, ela também amplia pertencimento, reduz vulnerabilidades e abre caminhos de futuro.', 'Cada treino pode abrir caminho para um futuro melhor.'],
  ['fight-gallery', 'Modalidades que formam cidadãos.', 'Atletas e projetos', 'Muay thai, boxe, jiu-jitsu, kickboxing, wrestling, natação, futebol e tênis de mesa fazem parte da rede apoiada pelo mandato. O incentivo chega em materiais, equipamentos, estrutura, divulgação e articulação de oportunidades. O resultado aparece no tatame, na quadra, na piscina e, principalmente, na autoestima de quem passa a se enxergar capaz.', 'Disciplina, convivência e respeito também são políticas públicas.'],
  ['fight-network', 'Amigos da Elite, HM Clan e Vila Zilda.', 'Entidades esportivas', 'As emendas fortalecem instituições como Amigos da Elite, HM Clan e Sociedade Representativa da Vila Zilda. São projetos que oferecem treino, convivência, festivais, modalidades esportivas e referência positiva para a juventude. O apoio público ajuda quem já está no território a ampliar alcance, organizar estrutura e manter portas abertas.', 'Uma rede forte transforma talento em oportunidade.'],
  ['timeline', 'Saúde com acesso e futuro.', 'Saúde pública', 'Na saúde, Val defende a implantação da telemedicina, cobra mutirões de atendimento especializado e acompanha os avanços do futuro Hospital Municipal. Também propõe ampliar tratamentos, garantir medicamentos, reduzir filas e fortalecer a rede pública. A prioridade é simples: fazer o serviço chegar mais rápido, com respeito e acompanhamento.', 'Saúde digna começa com acesso, escuta e acompanhamento.'],
  ['projects', 'Lei nº 5.303: microchipagem gratuita.', 'Proteção animal', 'A causa animal ganhou uma conquista importante com a Lei nº 5.303, que prevê microchipagem gratuita de cães e gatos e cadastro no Simpatinhas. O mandato também defende castrações, atendimento veterinário, apoio a protetores independentes, fortalecimento de ONGs e combate ao abandono. Cuidado animal também é saúde pública e responsabilidade coletiva.', 'Cuidar dos animais também é cuidar da cidade.'],
  ['commitments', 'Água, saneamento e fiscalização.', 'Serviços públicos', "Val atua na cobrança de soluções para falta d'água, baixa pressão, vazamentos e interrupções sem justificativa. Também apresenta indicações para desassoreamento de rios e canais, buscando reduzir alagamentos e melhorar a qualidade urbana. Fiscalizar serviço essencial é defender dignidade no cotidiano dos bairros.", 'Problema recorrente precisa de cobrança constante.'],
  ['projects', 'Direitos das mulheres e rede de proteção.', 'Disque 180', 'A divulgação obrigatória do Disque 180 amplia o acesso à informação para mulheres vítimas de violência. A atuação também inclui conscientização, prevenção e apoio ao fortalecimento da rede municipal de proteção. Quando a informação aparece em locais de circulação, a ajuda fica mais próxima de quem pode estar em situação de risco.', 'Informação salva vidas e aproxima ajuda.'],
  ['visual-diary', 'Empreendedorismo e geração de renda.', 'Desenvolvimento', 'O mandato trabalha pela modernização das regras do comércio eletrônico municipal, apoio aos pequenos empreendedores, desburocratização e criação de oportunidades para comerciantes, trabalhadores locais e novas iniciativas econômicas. Desenvolver Guarujá também é valorizar quem empreende, emprega e movimenta a economia da cidade.', 'Desenvolver é abrir caminho para quem trabalha.'],
  ['participation', 'Da escuta ao resultado.', 'Como trabalhamos', 'As demandas chegam pelas ruas, pelo gabinete e pelos canais digitais. A partir daí, o mandato registra, verifica, fiscaliza, propõe encaminhamentos e presta contas para que a população acompanhe cada etapa. O trabalho público precisa ser claro: ouvir, agir, acompanhar e mostrar o que aconteceu depois da conversa.', 'Transparência é mostrar o que aconteceu depois da conversa.'],
  ['projects', 'Terceiro setor: rede que chega onde a cidade precisa.', 'Entidades parceiras', 'As emendas destinadas ao terceiro setor fortalecem instituições que já atuam no território, conhecem as famílias e sustentam atendimentos essenciais. APAAG, Projeto Universo, Pequenos Herdeiros, Instituto Albuquerque, Formando Cidadão e outras iniciativas ajudam a transformar recurso público em cuidado direto, acompanhamento e oportunidade.', 'Quando a rede local é fortalecida, a política pública chega mais perto.'],
  ['visual-diary', 'Educação, inclusão e rotina escolar.', 'Escolas e famílias', 'A pauta da educação inclusiva envolve professores preparados, ambiente acolhedor, comunicação acessível e respeito às diferenças. O mandato defende formação continuada sobre autismo, adaptação de sinais escolares, materiais adequados e diálogo permanente com famílias, profissionais e instituições para que inclusão seja prática diária.', 'A escola inclusiva reconhece cada aluno como parte da cidade.'],
  ['commitments', 'Fiscalização que acompanha o problema até a resposta.', 'Serviço público', 'Fiscalizar é mais do que apontar falhas: é registrar, cobrar, acompanhar e prestar contas. Falta d água, iluminação, zeladoria, segurança, saúde e infraestrutura exigem presença constante. O mandato transforma reclamações recorrentes em indicações, cobranças formais e acompanhamento das providências junto aos órgãos responsáveis.', 'Demanda recebida precisa virar caminho de solução.'],
  ['projects', 'Proteção animal com prevenção e responsabilidade.', 'Causa animal', 'Microchipagem, castração, atendimento veterinário, cadastro no Simpatinhas e apoio a protetores formam uma política mais responsável para cães e gatos. A causa animal também envolve saúde pública, educação contra o abandono e fortalecimento de quem atua diariamente no resgate, cuidado e adoção responsável.', 'Cuidar dos animais é cuidar das famílias e dos bairros.'],
  ['timeline', 'Segurança, tecnologia e presença preventiva.', 'Videomonitoramento', 'O investimento em videomonitoramento fortalece a prevenção, melhora a resposta do poder público e amplia a sensação de segurança. A parceria para destinar R$ 2 milhões à área mostra como uma demanda local pode ganhar força quando existe articulação entre Guarujá e Brasília.', 'Segurança pública também se constrói com planejamento e tecnologia.'],
  ['participation', 'Prestação de contas permanente.', 'Transparência', 'A revista é uma parte da prestação de contas, mas o acompanhamento precisa continuar depois da leitura. O gabinete segue aberto para receber sugestões, apresentar encaminhamentos, explicar projetos e ouvir críticas. Participação popular ajuda o mandato a corrigir rotas, definir prioridades e manter o trabalho conectado à vida real.', 'Transparência é compromisso contínuo, não peça de ocasião.'],
  ['final-back-cover', 'O gabinete está de portas abertas.', 'Faça parte', 'Envie sugestões, acompanhe projetos, participe das decisões que impactam a cidade e cobre resultados. O mandato existe para ouvir, agir e prestar contas de forma clara à população de Guarujá. A revista é um convite para acompanhar de perto cada pauta, cada recurso e cada compromisso assumido.', 'Presença que cuida. Trabalho que transforma.'],
];

export const fallbackPages: MagazinePage[] = rows.map((row, index) => ({
  id: `fallback-${index + 1}`,
  page_number: index + 1,
  template: row[0],
  title: row[1],
  subtitle: row[2],
  body: row[3],
  quote: row[4] || null,
  background: null,
  elements: {},
  is_published: true,
}));


